### ISSUE TITLE
Error running electron-installer-dmg

### ISSUE THREAD

**Issue by artemgurzhii** [mongodb-js/electron-installer-dmg#17]
Running `electron-installer-dmg AppName.app OutputName` getting following ouput
```bash
{ Error: spawn bless ENOENT
    at exports._errnoException (util.js:1034:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn bless',
  path: 'bless',
  spawnargs:
   [ '--folder',

     '/Volumes/OutputName',
     '--openfolder',
     '/Volumes/OutputName' ],
  cmd: 'bless --folder /Volumes/OutputName --openfolder /Volumes/OutputName',
  stdout: '',
  stderr: '' }
```

**Comment by artemgurzhii** [comment]
As I have found out, this problem is caused by [appdmg](https://github.com/LinusU/node-appdmg), which you use to build dmg apps. Closing!
